Exception: Added simple shared std::string exception.
The constructor arguments are passed to the std::string which is allocated
dynamically and shared via a std::shared_ptr<std::string const> among all
copies of the exception.